version: "3.8"

services:
  app:
    build: .
    container_name: debate_app
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - "127.0.0.1:8000:80" # Only accessible locally
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped
    # No ports exposed to host - only accessible through internal network

  db:
    image: mysql:8.0
    container_name: debate_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-time-zone=+01:00",
      ]
    ports:
      - "127.0.0.1:3308:3306" # Changed from 3306 to 3308
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
